### ISSUE TITLE
ES6 syntax, there is a way to use react-window-mixins as not mixin?

### ISSUE THREAD

**Issue by eriknyk** [szymonkaliski/react-window-mixins#3]
Hi,
I'm using React ES6 syntax,
and there there is not mixins, so there is a way to use react-window-mixins without mixins?
sounds contradictory since the module is named "react-window-mixins"  but anyway.

Best regards.

**Comment by szymonkaliski** [comment]
Yes, when using ES6 classes instead of React.createClass you loose ability to use mixins, I stumbled upon this: https://github.com/brigand/react-mixin but haven't tasted it, looks like it could help.
