### ISSUE TITLE
onBeforeUnload accessed but not fired

### ISSUE THREAD

**Issue by pabloDon** [szymonkaliski/react-window-mixins#4]
I have added the module and copied the code to fire onBeforeUnload event:

```
mixins: [ OnUnload ],

    onUnload: function() {
        // Clean up any resources
    },

    onBeforeUnload: function() {
        return 'Are you sure you want to leave the page?';
    },
```

I have tried it on Chrome and Firefox, but nothing fires... I've debug it, and I see that the method is invoked (many times indeed), but nothing happens

**Comment by szymonkaliski** [comment]
We had similar discussion earlier: https://github.com/szymonkaliski/react-window-mixins/issues/2 Let me know if it helps?

**Comment by szymonkaliski** [comment]
No info for long time, closing for now, feel free to reopen though! :)
